// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_moiVq5mSqwfUNetWqHVjN6FjDHvo0t4',
    appId: '1:1098692272868:web:911cf5b3fc8419f53a42f1',
    messagingSenderId: '1098692272868',
    projectId: 'bingetime-96c40',
    authDomain: 'bingetime-96c40.firebaseapp.com',
    storageBucket: 'bingetime-96c40.appspot.com',
    measurementId: 'G-V0SG6Q15RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi5xdCLq7M5bj5W1opEw-OBZa1Z31ZPtI',
    appId: '1:1098692272868:android:41f2be4551e403853a42f1',
    messagingSenderId: '1098692272868',
    projectId: 'bingetime-96c40',
    storageBucket: 'bingetime-96c40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbuCL0Gx43VBnDw2eWSjPWGFg-ms_NkJ0',
    appId: '1:1098692272868:ios:acf14de4fbe562c23a42f1',
    messagingSenderId: '1098692272868',
    projectId: 'bingetime-96c40',
    storageBucket: 'bingetime-96c40.appspot.com',
    iosClientId: '1098692272868-tjtq2b52kf17f45r50qla7ebopr7t00e.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesapp',
  );
}
